### ISSUE TITLE
[Proposal] Integrating Dune Analytics as a Data Provider

### ISSUE THREAD

**Issue by leosayous21** [sismo-core/sismo-hub#1252]
# Integrating Dune Analytics as a Data Provider

Dune Analytics has recently launched an API that we believe would be perfect for integrating with Sismo Hub. The API is robust, reliable and provides an easy-to-use interface for querying, executing and checking the status of executions.

https://dune.com/docs/api/quick-start/api-js/#getting-set-up

Incorporating Dune Analytics into the Sismo Hub would bring several benefits for Group Generators as it provides a new way to access and query data.

### Generic Interface

It should be very easy to retrieve and use the data from the query directly inside our group generator.

Proposed interface:
```typescript
// declare the dune analytics provider 
const duneAnalytics = new dataProviders.DuneAnalyticsProvider();

// declare your query id
const queryId = 156895;

// Retrieve the data from the query. The retrieved Data will be an array typed with the type template T
const queryData: T[] = await duneAnalytics.executeQuery<T>(queryId);
```

### Integration in the factory

We should be able to use the Data Provider inside the [Sismo Factory](https://factory.sismo.io/). 
For instance, we could create a function that retrieves addresses from a query.

Proposed factory function: `Get addresses of query` 
With 2 inputs:
- `Query Id`: the query id of the query you want to retrieve your data from
- `Address Column Name`: the column you want to use as the account identifier for the group

## Handling API Key

Currently, we utilize environment variables to manage API Keys. An illustration of how to handle API Keys using the `SubgraphDecentralizedServiceProvider` can be found at https://github.com/sismo-core/sismo-hub/blob/main/group-generators/helpers/data-providers/subgraph/decentralized-service.provider.ts#L21 

## Example interface

<details>
<summary>Example use case: NounsDAO auction winners</summary>
Let's consider a practical scenario: we want to create a group that consists of all the Nouns DAO auction winners using the Dune analytics provider.
NounsDAO currently has a Dune Dashboard at https://dune.com/aaaaaaaaaa/NounsDAO, which has a Query that meets our needs directly: https://dune.com/queries/156895 
This query has an Id:  `156895`.

Within our Group Generator, we can write the following code:

```typescript
const generator: GroupGenerator = {
  generationFrequency: GenerationFrequency.Daily,
  
  generate: async (context: GenerationContext): Promise<GroupWithData[]> => {
  
    const duneAnalytics = new dataProviders.DuneAnalyticsProvider();

    // Let's define the result type of the query
    type DailyAuctionType = {
      date: string;
      nounId: number;
      winner: string;
      paid: number;
    }

    // Set the Query ID
    const nounsDailyAuctionQueryId = 156895;

    // Retrieve data from Dune Analytics
    const dailyAuctionData = await duneAnalytics.executeQuery<DailyAuctionType>(nounsDailyAuctionQueryId);

    // Use the data in the Group Generator
    const data: FetchedData = {};
    for(const auction of dailyAuctionData) {
      data[auction.winner] = 1;
    }

    return [
      {
        name: "nouns-daily-auction",
        timestamp: context.timestamp,
        data,
        valueType: ValueType.Score,
        tags: [Tags.User, Tags.Mainnet, Tags.NFT],
      },
    ];
  },
};
```

</details>

**Comment by sampolgar** [comment]
- would you like to use the Sismo rest provider or use axios?
- Dune is releasing their developer API this month, though can't test my work yet.
If anyone has a paid account API to share with me for testing that would be great!

**Comment by leosayous21** [comment]
@sampolgar going to send you one!

**Comment by sampolgar** [comment]
About 2 days away from being ready.

I need to add 
- support for query parameters for Dune query [examples here](https://dune.com/docs/api/quick-start/api-ready-queries/)
- address count function & interface-schema.json for the Sismo Factory
- test cases
- move from my git to the sismo hub
progress [here](https://github.com/sampolgar/sismo-dune-analytics)

**Comment by sampolgar** [comment]
Sorry for the delay!!! A few more days, I'm working through catching errors & displaying appropriate logs for when
- api key is incorrect
- queryid is incorrect
- query parameter is incorrect
- field to fetch is incorrect 
- no results returned

**Comment by sampolgar** [comment]
**Update**
Group generation now working for the 2 types of queries, 1) only using queryId and 2) queryId with parameters

1) Group Generation with QueryId
- using nouns auction query https://dune.com/queries/2034748  (I reduced the size of the output to 4 addresses for testing)
- Group Generator here: https://github.com/sampolgar/sismo-hub/tree/dataprovider-dune/group-generators/generators/sp-dune-nounauction

2) Group Generation with QueryID & Parameters
- using ERC20 contract querhy https://dune.com/queries/1616880
- Group Generator here: https://github.com/sampolgar/sismo-hub/tree/dataprovider-dune/group-generators/generators/sp-dune-queryparameters
- This is what query parameters look like in Dune
![CleanShot 2023-03-07 at 22 33 50](https://user-images.githubusercontent.com/39210767/223410721-1f1e9d00-f3c3-4d15-b778-80c5afc524d7.png)

I'll now work on the interface schema and factory compatability

**Comment by sampolgar** [comment]
How should we handle the Argument name/example in the factory?

Example
Function name: getDuneQueryResults
Argument Explanation: "Your Dune queryId and if available, your query parameters. If your query doesn't use queryParameters, you can leave the object empty e.g. queryParameters: {}"
Argument Example: {queryId: 2034748, queryParameters: {address: "0x1234"} }

**Comment by leosayous21** [comment]
> How should we handle the Argument name/example in the factory?
> 
> Example Function name: getDuneQueryResults Argument Explanation: "Your Dune queryId and if available, your query parameters. If your query doesn't use queryParameters, you can leave the object empty e.g. queryParameters: {}" Argument Example: {queryId: 2034748, queryParameters: {address: "0x1234"} }

Yes for me we always need the "queryId" argument. And for the queryParameters I agree with you that a json that can be empty (like that "" or "{}") will work 

We are going to update the schema to add a "required" key for each argument. For instance here you can see for the "getFollowersOfSpace" that we have a "required": "false", argument https://github.com/sismo-core/sismo-hub/issues/1431

**Comment by sampolgar** [comment]
Thanks @leosayous21 , the required field will work well.

Do you have a preference for including both options in one function or 2 separate functions?

Here's [a mockup](https://www.figma.com/file/5ZjHMtQtJY1YMsOMmrmTc2/Sismo-Dune-Analytics?node-id=2%3A13) of the factory user experience for either scenario.

My opinion is separating the functions (Option 2) gives users 2 distinct examples to look at and understand what they need to put there for either scenario. This might be more clear for the user.

**Comment by leosayous21** [comment]
The Mockup is very nice to understand! Thanks 🙏

I agree with you that it's more easy to use with the Option2 as we don't need to understand a the more complex part. It's up to the user that is not satisfied with the first one that can dig into the second one to see if that matches their need

**Comment by MartinGbz** [comment]
Hey @sampolgar 

Thanks a lot for your contribution to the Sismo Hub! 💜
Can you contact me on Discord (martingbz.eth#3809) or on Twitter (@0xMartinGbz) to discuss about the bounty payment process?

Also, your contribution makes you eligible to mint the [Sismo Contributor ZK Badge level 3](https://app.sismo.io/?badge=sismo-contributor-zk-badge) 🙌
