### ISSUE TITLE
Add possibility to cancel a request in Sismo Factory

### ISSUE THREAD

**Issue by milstan** [sismo-core/sismo-hub#1350]
## Description
Once a user submits a request to generate their Sismo Badge, during the waiting period (up to 48h), the user might change their mind and wish to cancel (or modify) the request. However, currently there seems to be no button to do so.

## Expected Behavior
Add a cancel button for pending requests (with a "are you sure to want to cancel" confirmation step) to Sismo Factory interface. Cancel the associated pull request and refund the funds.

## Actual Behavior
The user must wait (and can't change anything).

## Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/317424/220942449-a3700e40-87ae-49df-81b8-a1a1d2a253b5.png)

**Comment by leosayous21** [comment]
I'm closing the issue for now
