### ISSUE TITLE
[Proposal] Integrate 101 as a Data Provider 

### ISSUE THREAD

**Issue by ZKentin** [sismo-core/sismo-hub#1426]
Integrate [101](https://101.xyz/) as a Data Provider will enable to create new Groups from holders of a specific 101 Course NFT.

### Specifications

```jsx
{
  "name": "101",
  "iconUrl": "",
  "providerClassName": "101Provider",
  "functions": [
    {
      "name": "Get holders of course NFT",
      "functionName": "TODO",
      "countFunctionName": "TODO",
      "description": "Returns all holders of a specific 101 course",
      "args": [
        {
          "name": "course",
          "argName": "TODO",
          "type": "string",
          "required": "true",
          "example": "TODO",
          "description": "A specific course identifier"
        }
      ]
    }
  ]
}
```

### Tips on how to integrate the Data Provider

A 101 Course Token is a non-transferrable ERC-721 NFT minted on Polygon or Celo Chain with [these](https://intercom.help/101xyz/en/articles/6925861-about-our-badges) contract addresses.

The easiest way to extract addresses for each 101 Course NFT is by using [101 Subgraph](https://intercom.help/101xyz/en/articles/6925922-getting-badge-data-with-our-subgraph).

Have a look at [Sismo documentation](https://docs.sismo.io/sismo-docs/technical-documentation/sismo-hub/data-providers) to understand what is a Data Provider, and checkout the [tutorial](https://docs.sismo.io/sismo-docs/tutorials/create-your-data-provider-developers) to know how to integrate a Data Provider.

Have fun!

**Comment by MartinGbz** [comment]
Hey @mme022

Again, thanks a lot for your contribution to the Sismo Hub! 💜
You can still contact me on Discord (martingbz.eth#3809) or on Twitter (@0xMartinGbz) to discuss about the bounty payment process. :)
