### ISSUE TITLE
[Proposal] Integrate Unlock as a Data Provider 

### ISSUE THREAD

**Issue by ZKentin** [sismo-core/sismo-hub#1428]
Integrate [Unlock](https://unlock-protocol.com/) as a Data Provider will enable to create new Groups from holders of a specific Lock NFT.

### Specifications

```jsx
{
  "name": "Unlock",
  "iconUrl": "",
  "providerClassName": "UnlockProvider",
  "functions": [
    {
      "name": "Get holders of lock NFT",
      "functionName": "TODO",
      "countFunctionName": "TODO",
      "description": "Returns all holders of a specific lock",
      "args": [
        {
          "name": "lock",
          "argName": "TODO",
          "type": "string",
          "required": "true",
          "example": "TODO",
          "description": "A specific lock contract address"
        }
      ]
    }
  ]
}
```

### Tips on how to integrate the Data Provider

The easiest way to extract addresses for each Lock NFT is by using Unlock [Subgraph](https://docs.unlock-protocol.com/tools/subgraph/).

Have a look at [Sismo documentation](https://docs.sismo.io/sismo-docs/technical-documentation/sismo-hub/data-providers) to understand what is a Data Provider, and checkout the [tutorial](https://docs.sismo.io/sismo-docs/tutorials/create-your-data-provider-developers) to know how to integrate a Data Provider.

Have fun!

**Comment by MartinGbz** [comment]
The PR https://github.com/sismo-core/sismo-hub/pull/1680 has been merged
