### ISSUE TITLE
[Proposal] Integrate GitPOAP as a Data Provider 

### ISSUE THREAD

**Issue by ZKentin** [sismo-core/sismo-hub#1430]
Integrate [GitPOAP](https://www.gitpoap.io/) as a Data Provider will enable to create new Groups from GitPOAP holders of a specific Repository.

### Specifications

```jsx
{
  "name": "GitPOAP",
  "iconUrl": "",
  "providerClassName": "GitPOAPProvider",
  "functions": [
    {
      "name": "Get holders of repository",
      "functionName": "TODO",
      "countFunctionName": "TODO",
      "description": "Returns all holders of any GitPOAP of a specific repository",
      "args": [
        {
          "name": "repository",
          "argName": "TODO",
          "type": "string",
          "example": "ethereum-org-website",
          "description": "A specific repository identifier - gitpoap.io/repos"
        }
      ]
    }
  ]
}
```

### Tips on how to integrate the Data Provider

A GitPOAP Token is a transferrable ERC-721 NFT minted on Gnosis Chain.

The easiest way to extract the list of addresses is by using [GitPOAP API](https://docs.gitpoap.io/api).

Have a look at [Sismo documentation](https://docs.sismo.io/sismo-docs/technical-documentation/sismo-hub/data-providers) to understand what is a Data Provider, and checkout the [tutorial](https://docs.sismo.io/sismo-docs/tutorials/create-your-data-provider-developers) to know how to integrate a Data Provider.

Have fun!

**Comment by MartinGbz** [comment]
Hi @MarkuSchick @mme022 @3Vis3 
Thanks a lot for your contribution to the Sismo Hub! 💜
Can you contact me on Discord (martingbz.eth#3809) or on Twitter (@0xMartinGbz) to discuss about the bounty payment process?

Also, your contribution makes you eligible to mint the [Sismo Contributor ZK Badge level 3](https://app.sismo.io/?badge=sismo-contributor-zk-badge) 🙌
