### ISSUE TITLE
[Proposal] Integrate DegenScore as a Data Provider 

### ISSUE THREAD

**Issue by ZKentin** [sismo-core/sismo-hub#1432]
Integrate [DegenScore](https://degenscore.com/cafe) as a Data Provider will enable to create new Groups from holders of a Beacon Token above a min score and with a specific trait.

A Beacon Token is a non-transferable ERC-1155 NFT that is the on-chain proof of achievement of a DegenScore > 700, ensuring that holders are top crypto on-chain users.

Here is how you can get your [Beacon Token](https://degenscore.com/beacon). More detail on Beacon traits [here](https://docs.degenscore.com/beacon/integration/traits-reference).

### Specifications

```jsx
{
  "name": "DegenScore",
  "iconUrl": "",
  "providerClassName": "DegenScoreProvider",
  "functions": [
    {
      "name": "Get holders of beacon",
      "functionName": "TODO",
      "countFunctionName": "TODO",
      "description": "Returns all holders of a beacon above a min score and with a specific trait",
      "args": [
        {
          "name": "score",
          "argName": "TODO",
          "type": "TODO",
          "example": "730",
          "description": "A minimum beacon score"
        },
        {
          "name": "trait",
          "argName": "TODO",
          "type": "TODO",
          "example": "TODO",
          "description": "A specific trait identifier"
        }
      ]
    }
  ]
}
```

### Tips on how to integrate the Data Provider

Beacon Token is minted on Ethereum with [this](https://docs.degenscore.com/beacon/integration/on-chain) contract address.

The easiest way to extract addresses of Beacon holders is based on their unique Token ID, and verify that the Beacon is still true by using [DegenScore API](https://docs.degenscore.com/api#tag/BeaconService).

To get the score, you can get the balance of ERC-1155 NFTs of a Beacon holder corresponding to this [Token ID](https://etherscan.io/token/0x0521fa0bf785ae9759c7cb3cbe7512ebf20fbdaa?a=121371448299756538184036965).

To get the traits, you have to look at the attributes of the unique Token ID of the Beacon holder.

Have a look at [Sismo documentation](https://docs.sismo.io/sismo-docs/technical-documentation/sismo-hub/data-providers) to understand what is a Data Provider, and checkout the [tutorial](https://docs.sismo.io/sismo-docs/tutorials/create-your-data-provider-developers) to know how to integrate a Data Provider.

Have fun!

**Comment by mme022** [comment]
I spent some time looking into this now. And as I understand the desired specs are not that easy to fetch.
A good approach could be:
- fetching all token holders and balances from ERC1155 over all tokenIds -> data needs to be retrieved by the events, the same way OpenSea keeps track
- calling beaconDataOf(address) on tokencontract for fetched holders to retrieve beaconId
- calling DegenScore API for each beaconId retrieved
- filtering the results on score (balance) and trait of their unique beaconId

Thanks @Baoufa for taking time to check this with me.

**Comment by ZKentin** [comment]
Thanks a lot for your feedback :) Indeed, it's a bit complicated, as a first step let's try to get the beacon holders with an optional arg min score. Let's keep traits for later it's less important!
Have a look at their API 'List Beacons' call. 
Cheers :)

**Comment by MartinGbz** [comment]
Hey @MarkuSchick @mme022 @3Vis3

Thanks a lot for your contribution to the Sismo Hub! 💜
Can you contact me on Discord (martingbz.eth#3809) or on Twitter (@0xMartinGbz) to discuss about the bounty payment process?

Also, your contribution makes you eligible to mint the [Sismo Contributor ZK Badge level 3](https://app.sismo.io/?badge=sismo-contributor-zk-badge) 🙌
