### ISSUE TITLE
[Proposal] Integrate Yup as a Data Provider 

### ISSUE THREAD

**Issue by ZKentin** [sismo-core/sismo-hub#1433]
Integrate [Yup](https://yup.io/) as a Data Provider will enable to create new Groups from Yup users having top on-chain social value.

The Yup Score provides a reputation metric by aggregating on-chain actions and ranking between 1-100. The weight of each action is determined by its social value.

### Specifications

```jsx
{
  "name": "Yup",
  "iconUrl": "",
  "providerClassName": "YupProvider",
  "functions": [
    {
      "name": "Get users",
      "functionName": "TODO",
      "countFunctionName": "TODO",
      "description": "Returns all Yup users above a global min score or min score of a specific adapter",
      "args": [
        {
          "name": "score",
          "argName": "TODO",
          "type": "TODO",
          "required": "false",
          "example": "80",
          "description": "A minimum Yup score 1-100"
        },
        {
          "name": "adapter",
          "argName": "TODO",
          "type": "TODO",
          "required": "false",
          "example": "TODO",
          "description": "A specific adapter identifier"
        }
      ]
    }
  ]
}
```

### Tips on how to integrate the Data Provider

The easiest way to extract the list of addresses of Yup users is by using [Yup API](https://docs.yup.io/protocol/yup-api).

To get the global Yup score and the score for each Adapter, you can use their [Yup Score API](https://docs.yup.io/protocol/yup-score/score-api).

Have a look at [Sismo documentation](https://docs.sismo.io/sismo-docs/technical-documentation/sismo-hub/data-providers) to understand what is a Data Provider, and checkout the [tutorial](https://docs.sismo.io/sismo-docs/tutorials/create-your-data-provider-developers) to know how to integrate a Data Provider.

Have fun!

**Comment by sampolgar** [comment]
Hi @ZKentin 
Maybe I'm missing something, what I can see is the score api needs to specify 1 user e.g. `https://api.yup.io/score?address=vitalik.eth` which returns the reputation for the 1 user e.g.
```
{
    "data": {
        "id": "0xd8da6bf26964af9d7eed9e03e53415d37aa96045",
        "yup_score": 86.3919953932,
        "blacklisted": false,
        "expiration": "2023-04-25T17:12:59.732814Z",
        "score_data": {
            "ens": {
                "score": 71,
                "primary": "vitalik.eth",
                "domains": [...
```

The adapters api `/score/weights` returns 
```
{
    "data": {
        "ens": 0.14,
        "eth_balance": 0.15,
        "polygon_balance": 0.15,
        "polygon_nfts": 0.16,
        "gnosis_nfts": 0.064,
        "eth_nfts": 0.096,
        "eth_activity": 0.08,
        "recent_polygon_transfers": 0.04,
        "recent_eth_transfers": 0.04,
        "snapshot_votes": 0.04,
        "eth_erc20_tokens": 0.04
    }
}
```

and the accounts `http://api.yup.io/accounts/darren_yup` returns something like this

```
{
    "_id": "darrenyupxxx",
    "__v": 1,
    "avatar": "https://ipfs-file-backups.s3.amazonaws.com/QmdbPRzhgya7JXaJAKLC7cWm4Gbox3BJoVViujq7SNX5Tp",
    "bio": "memento mori",
    "eosname": "darrenyupxxx",
    "fullname": "Darren",
    "skey": "3461924983",
    "username": "darren_yup",
    "balance": {
        "YUP": 6218.010246
    },
    "twitterInfo": {
        "username": "darren_yupio",
        "userId": "1277685255256674304",
        "isMirror": false,
        "isSuspended": false
    },
```
**Questions**

- Did you want this data provider to query multiple users or just 1 user at a time?
- If only 1 user, we can allow the user to add a list and then we query each address individually to find their yup reputation and then filter, etc, we are limited to 50 requests per minute

Let me know if I've missed something.

**Comment by sampolgar** [comment]
Looping @MartinGbz for help answering

**Comment by MartinGbz** [comment]
> Looping @MartinGbz for help answering

Hey @sampolgar sorry for the very late answer.
If there are no possibilities to get directly a list of addresses, then we won't do it.
Unfortunately It's a problem we have with a lot of scorer provider :/

I'm closing this issue then
