### ISSUE TITLE
[Proposal] Integrate Orange as a Data Provider 

### ISSUE THREAD

**Issue by ZKentin** [sismo-core/sismo-hub#1440]
Integrate [Orange](https://www.orangeprotocol.io/) as a Data Provider will enable to create new Groups from holders of a specific Orange Protocol Campaign NFT.

### Specifications

```jsx
{
  "name": "Orange",
  "iconUrl": "",
  "providerClassName": "OrangeProvider",
  "functions": [
    {
      "name": "Get holders of campaign NFT",
      "functionName": "TODO",
      "countFunctionName": "TODO",
      "description": "Returns all holders of a specific Orange Protocol campaign",
      "args": [
        {
          "name": "campaign",
          "argName": "TODO",
          "type": "string",
          "required": "true",
          "example": "TODO",
          "description": "A specific campaign identifier"
        }
      ]
    }
  ]
}
```

### Tips on how to integrate the Data Provider

Orange Protocol Badges are transferrable ERC-721 NFTs.

The easiest way to extract the list of addresses is by using [Orange Protocol API](https://docs.orangeprotocol.io/developers/get-campaign-info-using-api#getorangebycampaignid).

Have a look at [Sismo documentation](https://docs.sismo.io/sismo-docs/technical-documentation/sismo-hub/data-providers) to understand what is a Data Provider, and checkout the [tutorial](https://docs.sismo.io/sismo-docs/tutorials/create-your-data-provider-developers) to know how to integrate a Data Provider.

Have fun!

**Comment by mme022** [comment]
GM, I have requested an API key from Orange. Request is forwarded to their devs, will work on this as soon as they provide the key/endpoint.

**Comment by sampolgar** [comment]
@mme022 did you manage to get the api key? Lmk if you're not interested in this one

**Comment by mme022** [comment]
It's an ongoing process, but the devs of Sismo itself are doing the communication with Orange now.

**Comment by MartinGbz** [comment]
Hey, because we didn't have the necessary API Keys and endpoint, I'm closing the issue
