### ISSUE TITLE
[Proposal] Integrate Mirror as a Data Provider 

### ISSUE THREAD

**Issue by ZKentin** [sismo-core/sismo-hub#1444]
Integrate [Mirror](https://mirror.xyz/) as a Data Provider will enable to create new Groups from collectors of a specific Mirror post NFT.

### Specifications

```jsx
{
  "name": "Mirror",
  "iconUrl": "",
  "providerClassName": "MirrorProvider",
  "functions": [
    {
      "name": "Get collectors of post",
      "functionName": "TODO",
      "countFunctionName": "TODO",
      "description": "Returns all collectors of a specific Mirror post",
      "args": [
        {
          "name": "address",
          "argName": "TODO",
          "type": "string",
          "required": "true",
          "example": "TODO",
          "description": "A specific contract address of the post NFT"
        }
      ]
    }
  ]
}
```

### Tips on how to integrate the Data Provider

The easiest way to extract the list of addresses from a collected post NFT is by using BigQuery.

Here is a [tutorial](https://dev.mirror.xyz/GjssNdA6XK7VYynkvwDem3KYwPACSU9nDWpR5rei3hw) on using GraphQL to get data from Arweave. 

Have a look at [Sismo documentation](https://docs.sismo.io/sismo-docs/technical-documentation/sismo-hub/data-providers) to understand what is a Data Provider, and checkout the [tutorial](https://docs.sismo.io/sismo-docs/tutorials/create-your-data-provider-developers) to know how to integrate a Data Provider.

Have fun!

**Comment by MartinGbz** [comment]
Again, thanks a lot @sampolgar for your new contribution to the Sismo Hub! 💜
