### ISSUE TITLE
[Proposal] Integrate Paragraph as a Data Provider 

### ISSUE THREAD

**Issue by ZKentin** [sismo-core/sismo-hub#1445]
Integrate [Paragraph](https://paragraph.xyz/) as a Data Provider will enable to create new Groups from collectors of a specific Paragraph post NFT.

### Specifications

```jsx
{
  "name": "Paragraph",
  "iconUrl": "",
  "providerClassName": "ParagraphProvider",
  "functions": [
    {
      "name": "Get collectors of post",
      "functionName": "TODO",
      "countFunctionName": "TODO",
      "description": "Returns all collectors of a specific Paragraph post",
      "args": [
        {
          "name": "address",
          "argName": "TODO",
          "type": "string",
          "required": "true",
          "example": "TODO",
          "description": "A specific contract address of the post NFT"
        }
      ]
    }
  ]
}
```

### Tips on how to integrate the Data Provider

Paragraph NFTs are ERC-1155 minted on Polygon with [this](https://docs.paragraph.xyz/docs/development) contract address.

The easiest way to extract the list of addresses from a collected post NFT is by using BigQuery.

Here is a [tutorial](https://docs.paragraph.xyz/docs/integrations/arweave) on using GraphQL to get data from Arweave. 

Have a look at [Sismo documentation](https://docs.sismo.io/sismo-docs/technical-documentation/sismo-hub/data-providers) to understand what is a Data Provider, and checkout the [tutorial](https://docs.sismo.io/sismo-docs/tutorials/create-your-data-provider-developers) to know how to integrate a Data Provider.

Have fun!

**Comment by sampolgar** [comment]
Looks like the post collectibles are not yet available
https://docs.paragraph.xyz/docs/nfts "Turn your entire post into a collectible. Coming soon!"

**Comment by sampolgar** [comment]
Looks like there's content here: https://opensea.io/collection/paragraph-v2 I'll make a group

**Comment by MartinGbz** [comment]
Hey @sampolgar now that we have the Ankr Provider or the Token Provider, this issue is outdated.
I'm closing it
