### ISSUE TITLE
[Proposal] Create a Group from Humanbound Token holders

### ISSUE THREAD

**Issue by ZKentin** [sismo-core/sismo-hub#1447]
A [Humanbound Token](https://humanbound.xyz/) is a non-transferable ERC-721 NFT that is the on-chain representation of an off-chain KYC verified identity.

Creating the Humanbound Token Group will enable to generate new sybil-resistant Groups from members that are unique humans verified by a KYC.

### Specifications

Expected Group: list of all addresses holding a Humanbound Token. 

### Tips on how to create the Group

Humanbound Token is currently available on 4 chains: Ethereum, Polygon, Arbitrum and Optimism. Verified users are free to mint Humanbound Token on the 4 chains.

Humanbound Token is not account-bound, but for each human it is the same Token Id across chains. It is important to rely on the unicity of the Token Id to extract the corresponding unique wallet address. 

We invite you to check their [documentation](https://docs.humanbound.xyz/) for more information, especially [contract addresses](https://docs.humanbound.xyz/smart-contracts/deployed-contracts).

They don’t have an API, so the easiest way to extract the list of addresses is by using BigQuery (do no support Arbitrum & Optimism yet) & Etherscan.

Have a look at [Sismo documentation](https://docs.sismo.io/sismo-docs/tutorials/create-your-zk-badge-in-15-minutes-developers) to understand how to generate a Group.

Have fun!

**Comment by MartinGbz** [comment]
Again, thanks a lot @sampolgar for your new contribution to the Sismo Hub! 💜
