### ISSUE TITLE
[Proposal] Create a Group from kycDAO Token holders

### ISSUE THREAD

**Issue by ZKentin** [sismo-core/sismo-hub#1448]
A [kycDAO](https://kycdao.xyz/) Token is a non-transferable ERC-721 NFT that is the on-chain representation of an off-chain KYC verified identity.

Creating the kycDAO Token Group will enable to generate new sybil-resistant Groups from members that are unique humans verified by a KYC.

### Specifications

Expected Group: list of all addresses holding a kycDAO Token. 

### Tips on how to create the Group

kycDAO Token is currently available on [these](https://docs.kycdao.xyz/smartcontracts/) chains.

kycDAO smart contracts should be called to confirm that the address's kycNFT token is still valid.

The easiest way to extract the list of addresses is by using BigQuery.

Have a look at [Sismo documentation](https://docs.sismo.io/sismo-docs/tutorials/create-your-zk-badge-in-15-minutes-developers) to understand how to generate a Group.

Have fun!

**Comment by sampolgar** [comment]
KYCDAO is on Polygon, CELO, NEAR & Solana.
NEAR & Solana public addresses aren't in the same format as Ethereum. Is it right to assume we don't need these 2 chains addresses? @MartinGbz

**Comment by MartinGbz** [comment]
@sampolgar Indeed we can't use NEAR & Solana adresses. So yes let's keep the 2 EVM chains 👍

**Comment by MartinGbz** [comment]
It's merged, thanks! 🙌
