### ISSUE TITLE
[Proposal] Create a Group from UnstoppableDomains holders

### ISSUE THREAD

**Issue by ZKentin** [sismo-core/sismo-hub#1449]
[The Unstoppable Name Service](https://github.com/unstoppabledomains/uns) is a transferrable ERC-721 NFT representing ownership of an Unstoppable Domain Name Service.

Creating the UnstoppableDomains Group will enable to generate new Groups from UnstoppableDomains Name Service holders.

### Specifications

Expected Group: list of all addresses holding an Unstoppable Name Service. 

### Tips on how to create the Group

Unstoppable Name Service is minted on Ethereum and can be transferred to Polygon, with [these](https://github.com/unstoppabledomains/uns/blob/main/uns-config.json) contract addresses and the corresponding [list of network IDs](https://docs.unstoppabledomains.com/manage-domains/polygon-release-notes/).

The easiest way to extract the list of addresses is by using BigQuery and the on-chain Token ID.

Have a look at [Sismo documentation](https://docs.sismo.io/sismo-docs/tutorials/create-your-zk-badge-in-15-minutes-developers) to understand how to generate a group.

Have fun!

**Comment by MartinGbz** [comment]
PR: https://github.com/sismo-core/sismo-hub/pull/1765 merged ✅

Again, thanks @sampolgar for your contribution to the Sismo Hub! 💜
