### ISSUE TITLE
[Proposal] Create a Group from SismoENS holders

### ISSUE THREAD

**Issue by ZKentin** [sismo-core/sismo-hub#1451]
ENS Token is a transferable ERC-721 NFT that assigns human-readable addresses to ethereum wallets.

Creating the SismoENS Group will enable to generate new Groups from members holding a sismo.eth subdomain (e.g: dHadrien.sismo.eth).

### Specifications

Expected Group: list of all addresses holding a ENS sismo.eth subdomain. 

### Tips on how to create the Group

ENS Token is minted on Ethereum Chain.

Have a look at [Sismo documentation](https://docs.sismo.io/sismo-docs/tutorials/create-your-zk-badge-in-15-minutes-developers) to understand how to generate a group.

Have fun!

**Comment by sampolgar** [comment]
group made here: https://github.com/sismo-core/sismo-hub/pull/1767
