### ISSUE TITLE
[Proposal] Create a Group from POAP Event Token holders

### ISSUE THREAD

**Issue by ZKentin** [sismo-core/sismo-hub#1453]
Creating the POAP Event Token Group will enable to generate new sybil-resistant Groups from members that own a POAP Event.

### Specifications

Expected Group: list of all addresses holding a POAP Event Token. 

### Tips on how to create the Group

A POAP Event Token is a transferrable ERC-721 NFT minted on Gnosis Chain.

The easiest way to extract the list of addresses is by using [POAP API](https://documentation.poap.tech/docs).

Have a look at [Sismo documentation](https://docs.sismo.io/sismo-docs/tutorials/create-your-zk-badge-in-15-minutes-developers) to understand how to generate a group.

Have fun!

**Comment by sampolgar** [comment]
We have a POAP data provider, is this necessary? @MartinGbz

**Comment by MartinGbz** [comment]
> We have a POAP data provider, is this necessary? @MartinGbz

You are right sir, I'm closing the issue
