### ISSUE TITLE
[Proposal] Create a Group from GitPOAP Token holders

### ISSUE THREAD

**Issue by ZKentin** [sismo-core/sismo-hub#1454]
[GitPOAP](https://www.gitpoap.io/) is a contributor recognition platform that integrates POAP issuance into GitHub.

Creating the GitPOAP Token Group will enable to generate new Groups from members that own a GitPOAP.

### Specifications

Expected Group: list of all addresses holding a GitPOAP Token. 

### Tips on how to create the Group

A GitPOAP Token is a transferrable ERC-721 NFT minted on Gnosis Chain.

The easiest way to extract the list of addresses is by using [GitPOAP API](https://docs.gitpoap.io/api).

Have a look at [Sismo documentation](https://docs.sismo.io/sismo-docs/tutorials/create-your-zk-badge-in-15-minutes-developers) to understand how to generate a group.

Have fun!

**Comment by MartinGbz** [comment]
Implicitly realized with this issue: https://github.com/sismo-core/sismo-hub/issues/1430
I closed this issue
