### ISSUE TITLE
[Proposal] Create a Group from Yup users

### ISSUE THREAD

**Issue by ZKentin** [sismo-core/sismo-hub#1455]
Yup is extracting the best of Farcaster, Lens, Mirror, NFTs, Twitter, and all of web3 in one curated feed.

Creating the Yup Group will enable to generate new Groups from Yup users.

### Specifications

Expected Group: list of all addresses using Yup. 

### Tips on how to create the Group

The easiest way to extract the list of addresses is by using [Yup API](https://docs.yup.io/protocol/yup-api).

Have a look at [Sismo documentation](https://docs.sismo.io/sismo-docs/tutorials/create-your-zk-badge-in-15-minutes-developers) to understand how to generate a group.

Have fun!

**Comment by sampolgar** [comment]
Waiting for a response on the Yup data provider Q to do this one https://github.com/sismo-core/sismo-hub/issues/1433

**Comment by sampolgar** [comment]
The Yup knowledge base describes an API to extract all addresses - it doesn't exist in reality.
It appears there's no way to get "all" yup users, only a specific user.

<img width="348" alt="CleanShot 2023-05-10 at 21 05 55@2x" src="https://github.com/sismo-core/sismo-hub/assets/39210767/a564f8e9-4f3a-4064-8dfb-131292483014">
<img width="367" alt="CleanShot 2023-05-10 at 21 06 08@2x" src="https://github.com/sismo-core/sismo-hub/assets/39210767/7a0a37f1-3d47-4e50-9c77-c7cfad247625">

**Comment by MartinGbz** [comment]
Okay, thanks for the info!
Then, I'm closing this issue
