### ISSUE TITLE
A small typo on the badge explorer page

### ISSUE THREAD

**Issue by selversenguler** [sismo-core/sismo-hub#1469]
## Description
A small typo on the badge explorer page: Eligiblity instead of Eligibility

## Steps to Reproduce
Change Eligiblity to Eligibility

## Expected Behavior
Eligibility

## Actual Behavior
Eligiblity

## Screenshots (if applicable)
<img width="1710" alt="Screenshot 2023-03-06 at 01 36 04" src="https://user-images.githubusercontent.com/72295287/222995542-ac0d272e-da0e-4765-ba4f-a896615b2c6b.png">
<img width="568" alt="Screenshot 2023-03-06 at 01 36 32" src="https://user-images.githubusercontent.com/72295287/222995574-9aba1642-7eed-4109-9919-451dfb0f9a95.png">

## Additional Information
Node version: [e.g. v18.13.0]
Browser and version: [e.g. Chrome 88.0.4324.96]
Operating system: [e.g. MacOS Monterey ]

**Comment by MartinGbz** [comment]
Hey, sorry for the delay, good catch!
This problem has been fixed, thanks! 🙏
