### ISSUE TITLE
[Proposal] Create a Group from Binance Account Bound Token holders

### ISSUE THREAD

**Issue by ZKentin** [sismo-core/sismo-hub#1483]
A [Binance Account Bound Token](https://www.binance.com/en/BABT?source=header) is a non-transferable ERC-721 NFT that is the on-chain representation of an off-chain Binance KYC verified identity.

Creating the BinanceAccountBound Token Group will enable to generate new sybil-resistant Groups from members that are unique humans verified by a KYC.

### Specifications

Expected Group: list of all addresses holding a Binance Account Bound Token. 

### Tips on how to create the Group

Binance Account Bound Token is minted on BNB Chain with [this](https://bscscan.com/token/0x2b09d47d550061f995a3b5c6f0fd58005215d7c8) contract address.

The easiest way to extract the list of addresses is by using their [API](https://developers.binance.com/docs/babt/apis-spec).

Have a look at [Sismo documentation](https://docs.sismo.io/sismo-docs/tutorials/create-your-zk-badge-in-15-minutes-developers) to understand how to generate a group.

Have fun!

**Comment by MartinGbz** [comment]
Hey, yes because the Token Provider (which use BigQuery) and the Alchemy Provider doesn't support the BSC, you are free tu use the provider you want 😊
