### ISSUE TITLE
[Issue] Sismo Factory referencing 15 minute tutorial now unavailable

### ISSUE THREAD

**Issue by sampolgar** [sismo-core/sismo-hub#1518]
https://factory.sismo.io/create-group has a link to the 15 minute tutorial now taken down.

I think it might have changed to https://docs.sismo.io/sismo-docs/tutorials/sismo-hub/create-your-group

![CleanShot 2023-03-16 at 11 06 25](https://user-images.githubusercontent.com/39210767/225473741-fd3333f5-0eb4-4990-8beb-e7695988f67f.png)
![CleanShot 2023-03-16 at 11 06 52](https://user-images.githubusercontent.com/39210767/225473839-2119edda-59a4-498e-8ec6-0a2c55482b75.png)

**Comment by leosayous21** [comment]
Hey thanks for reporting this! @Baoufa will remove it! Will keep you in touch
