### ISSUE TITLE
[Proposal] dynamic graphql data provider

### ISSUE THREAD

**Issue by sampolgar** [sismo-core/sismo-hub#1619]
This data provider enables Factory users to insert 
- a graphql query
- endpoint
- JMESpath query to parse the graphql results and fetch the array

**Comment by sampolgar** [comment]
Data provider progress [here](https://github.com/sampolgar/sismo-hub/tree/dataprovider-dynamic-graphql/group-generators/helpers/data-providers/dynamic-graphql): 
Group generator progress [here](https://github.com/sampolgar/sismo-hub/blob/dataprovider-dynamic-graphql/group-generators/generators/dynamic-graphql/index.ts)

Considerations
- if the graphql query requires an api key, we could request this in the factory. Will a user want to include their API key in the factory? Is it safe/secure to do so?
- requires jmespath package `@types/jmespath`

Not yet supported
- paging for larger graphql queries, I'll work on that next

Any feedback will be greatly appreciated

**Comment by sampolgar** [comment]
Something like this
![CleanShot 2023-03-28 at 07 03 22](https://user-images.githubusercontent.com/39210767/228053761-0e7dd4e3-d741-4105-b9cd-db3551f67440.png)

**Comment by leosayous21** [comment]
Hello @sampolgar! 
I think it does the work :-).
- for the JMESPath you are talking about addresses here but what about the "value"? Do you have an idea for that? Maybe we start with only addresses for now? 
- for the GraphQL API Key input, for now we can't do it otherwise the secret would be in clear text in the sismo hub. We will improve this part in the future.
- For the Query Input, I think we will do a GraphQL query input other wise it's not very beautiful haha. We will be able to re-use it for the subgraph provider!

**Comment by sampolgar** [comment]
Hey @leosayous21!
- I think we focus on addresses for now and work out the value later when we know the format of different queries. Maybe JMES path can do it or maybe not
- Query Input would be great!

Pagination
- I'm having trouble adding pagination because the factory can only send a string format to the provider (not the GraphQL object). I tried using regex to remove/replace pagination and re-add it in, still not working.

I think having the Query Input as a GraphQL type / AST would help with pagination and adding attributes.

Here's the [data provider ](https://github.com/sampolgar/sismo-hub/tree/dataprovider-dynamic-graphql/group-generators/helpers/data-providers/dynamic-graphql) and the [group generator ](https://github.com/sampolgar/sismo-hub/tree/dataprovider-dynamic-graphql/group-generators/generators/dynamic-graphql) - the group generator has examples of queries and their JMESpath.

Is it ready for a PR?

**Comment by sampolgar** [comment]
Hey @leosayous21! Lmk if I can do anything else for this guy :)

**Comment by leosayous21** [comment]
Hey, sorry for the late reply!

- Agree with you, let's focus on addresses for now
- Let's keep the input as it is right now, we will update it whenever we have the Query Input 🙂 
- Let's do it without a pagination for now, it will address already most use cases. We will see how to handle pagination in the future. 

Yes, let's go for a PR! 💪
