### ISSUE TITLE
[Question] Badges based on onchain activity 

### ISSUE THREAD

**Issue by cincauhangus** [sismo-core/sismo-hub#1748]
Hi, Aaron from Philand here. 

I was wondering if it is possible to create a badge based on a connected account's activity, e.g. "Swapped 50 times on Uniswap v3". 

edit: Reading back on past issues & PRs, I noticed there was a Dune resolve but it was recently removed. I was hoping to run this query which gives the desired addresses - https://dune.com/queries/2443489

**Comment by cincauhangus** [comment]
@MartinGbz thanks for the guidance, I've created a PR for this!

**Comment by MartinGbz** [comment]
The PR has been merged, the group is generated and deployed ✅
